#!/bin/bash

if [ ! -d $HOME/.cargo ]; then
    curl https://sh.rustup.rs -sSf | sh -s -- --no-modify-path
fi
if ! command -v cargo >/dev/null; then
    source $HOME/.cargo/env
fi

crates=(
    topgrade
    starship
    du-dust
    exa
    tealdeer
    cargo-update
    ripgrep
    fd-find
    zoxide
)
cargo install ${crates[@]}
