export php_revshell="/usr/share/webshells/php/php-reverse-shell.php"
export rockyou="/usr/share/wordlists/rockyou.txt"
export dirlist_sm="/usr/share/wordlists/dirbuster/directory-list-2.3-small.txt"
export dirlist_md="/usr/share/wordlists/dirbuster/directory-list-lowercase-2.3-medium.txt"
export common="/usr/share/seclists/Discovery/Web-Content/common.txt"
export linpeas="/opt/linpeas.sh"
